name: learn gihub actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: print helo world
        run: echo "hello world"
        shell: bash
  windows:
    runs-on: windows-latest
    steps:
      - name: print dir
        run: dir
